---
title: "Topic Model"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Topic Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  eval = FALSE
)
```

```{r setup}
library(SefazCE)
library(tidyverse)
```

```{r}
glimpse(da_sefaz)
```

```{r}
da_sefaz$ementas[1]
```

```{r}
da_sefaz %>%
  mutate(
    topico = sample(1:3, n(), replace = TRUE)
  )
```


```{r}
da_sefaz_mini <- da_sefaz %>% 
  rownames_to_column(var = "documento_id") %>%
  select(documento_id, ementas)
```

## TF-IDF

```{r}
stopwords_juridicas <- c("art", "lei", "artigo", "nao")

da_sefaz_tfidf <- da_sefaz_mini %>%
  unnest_tokens(word, ementas) %>%
  filter(!word %in% c(stopwords::stopwords("pt", source = "snowball"), stopwords_juridicas)) %>%
  count(documento_id, word, sort = TRUE) %>%
  arrange(documento_id, desc(n)) %>%
  bind_tf_idf(word, documento_id, n)

da_sefaz_tfidf$tf_idf %>% log() %>% hist()

da_sefaz_tfidf <- da_sefaz_tfidf %>%
  filter(log(tf_idf) > -4)

glimpse(da_sefaz_tfidf)
```


```{r}
da_sefaz_tfidf %>%
  group_by(documento_id) %>%
  filter(documento_id %in% c(1,2,3,4)) %>%
  slice_max(tf_idf, n = 5) %>%
  ungroup() %>%
  ggplot(aes(tf_idf, fct_reorder(word, tf_idf), fill = documento_id)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~documento_id, ncol = 2, scales = "free_y") +
  labs(x = "tf-idf", y = NULL) +
  theme_minimal(20)
```

## LDA

```{r}
da_sefaz_dtm <- tidytext::cast_dtm(
  data = da_sefaz_tfidf, 
  document = documento_id, 
  term = word, 
  value = n
) %>% 
  tm::removeSparseTerms(1)
da_sefaz_dtm 
```


```{r}
library(topicmodels)
sefazce_lda <- LDA(da_sefaz_dtm, k = 4, control = list(seed = 1234))
sefazce_lda
```

```{r}
topicos <- tidy(sefazce_lda, matrix = "beta")

top_terms <- topicos %>%
  group_by(topic) %>%
  slice_max(beta, n = 7) %>% 
  ungroup() %>%
  arrange(topic, -beta)

nome_dos_topicos <- tribble(
  ~topico_id, ~topico_nome,
  1, "Omissão",
  2, "Crédito Tributário",
  3, "Autuação",
  4, "Mercadorias"
)

top_terms %>%
  mutate(term = reorder_within(term, beta, topic)) %>%
  left_join(nome_dos_topicos, by = c("topic" = "topico_id")) %>%
  ggplot(aes(beta, term, fill = factor(topico_nome))) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~ topico_nome, scales = "free") +
  scale_y_reordered() +
  theme_minimal(24)
```

